# Site settings
title: Matt Daniels
email: "mattd25 at uw dot edu"
description: >- # this means to ignore newlines until next setting
  Graduate student in economics at University of Washington.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MDaniels100
github_username:  mattdaniels

# Build settings
markdown: kramdown
theme: minima
cvstyle: kjhealy 
plugins:
  - jekyll-feed

#
#navigation:
 # -title: research
#  link: /research.html




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
